# EMBEDDED SERVER CONFIGURATION (ServerProperties)

server:
    port: 8083
    address: 0.0.0.0
    session-timeout: 30
    compression:
        enabled: true
    undertow:
        access-log-dir: /logs/access/
        access-log-enabled: false
        access-log-pattern: common
        max-post-size: 0
        buffer-size: 131072
        buffers-per-region:
        direct-buffers: false
        io-threads: 4
        worker-threads: 32

logging:
    path: /logs
    file: /logs/apicenter.log
    level:
       com:
          elise:
              apicenter:
                   controller: INFO
                   config: INFO
                   interceptor: INFO

http:
    timeout:
        conn: 4000
        request: 6000
        socket: 4000
    pool:
        max-total: 30
        route-total: 6
    retry-count: 1
    expect-continue-enable: true

spring:
    application:
      name: service-learning-api     #服务ID
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://10.0.98.100:3306/hq_school?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        password: root
        username: root
        driver-class-name: com.mysql.jdbc.Driver
        minimum-idle: 5
        maximum-pool-size: 20
        idle-timeout: 600000
        connection-timeout: 30000
        max-lifetime: 1800000
    redis:
        enabled: true
        # 指定连接工厂使用的Database index，默认为: 0
        database: 4
        # 指定Redis server host，默认为: localhost
        host: 10.0.98.100
        # 指定redis服务端端口，默认: 6379
        port: 6379
        # 指定Redis server的密码
        # password:
        use-pool: true
        pool:
              # 指定连接池最大的活跃连接数，-1表示无限，默认为8
              max-active: 8
              # 指定当连接池耗尽时，新获取连接需要等待的最大时间，以毫秒单位，-1表示无限等待
              max-wait: 5000
              # 指定连接池最大的空闲连接数，-1表示无限，默认为8
              min-idle: 8
              # sentinel:
                  # 指定redis server的名称
                  # master:
                  # 指定sentinel节点，逗号分隔，格式为host:port.
                  # nodes:
              # 指定连接超时时间，毫秒单位，默认为0
              timeout: 10000

local-info:
    school-id: kuaiji
    sso-host: http://10.0.98.80:8084     #http://10.0.98.14:8084 #SSO系统的请求路径,不区分业务线
    #sso-host: http://10.0.98.15:28087 #SSO系统的请求路径,区分业务线
    self-host: http://api.hqjy.com/service-adaptive-api #自适应系统的请求路径
    self-alg-host: http://api.hqjy.com/adaptive-learn-center #自适应算法服务的请求路径
    msg-host: http://dev.api.hqjy.cn/service-msg-api-test            #http://10.0.98.15:8666 #消息系统的请求路径
    max-offset: 20
    msg-max-offset: 10
    gensee-webcast-url: http://{genseeDomain}/webcast/site/entry/join-
    gensee-service-type: webcast
    gensee-verify-aging: 30000
    polyv-verify-url: http://183.63.120.222:8010/api/polyvOliveVerify
    olive-replay-url: http://p.bokecc.com/playvideo.bo?uid=FE7A65E6BE2EA539&playerid=CED4B0511C5D4992&playertype=1&autoStart=false&vid=
    replay-url: http://p.bokecc.com/playvideo.bo?uid=FE7A65E6BE2EA539&playerid=CED4B0511C5D4992&playertype=1&autoStart=false&vid=
    top-content-pic: http://xx.xx.xx.jpg
    customer-care-url: http://downt.ntalker.com/t2d/chat.php?siteid=kf_9005&settingid=wx_code&baseuri=http%3A%2F%2Fdl.ntalker.com%2Fjs%2Fxn6%2F
    msg_system_host: http://dev.api.hqjy.cn/service-msg-api-test      #消息系统地址
    apph5-url: http://10.0.98.15:8083   #跳转到H5页面地址
    itunes:             # iap 内购参数   0:沙盒测试         1:线上测试
      apple:
        config-param: 0

sso-info:
    sso-userinfo-url: http://10.0.98.80:8084/inner/userInfo
    sso-usertokendetail-url: http://10.0.98.80:8084/inner/userTokenDetail
    sso-usermobileno-url: http://10.0.98.80:8084/inner/userMobileNo
    sso-getbussinessid-url: http://10.0.98.80:8084/inner/getBussinessId

swagger:
    enable: true
    title-name: API Center 接口文档
    base-package: com.hq.learningapi.controller
    author: Glenn
    version: 1.0

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true                     # 设置微服务调用地址为IP优先（缺省为false）
    ipAddress: 10.0.98.30
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://admin:hqjymicro@10.0.98.17:8100/eureka/,http://admin:hqjymicro@10.0.98.17:8101/eureka/,http://admin:hqjymicro@10.0.98.17:8102/eureka/
    enabled: false



# IP 白名单
ip-white-list:
    filter-switch: false
    list:
        - 8.8.8.8
        - 0.0.0.0
        - 127.0.0.1
        - 0:0:0:0:0:0:0:1
        - 177.77.83.149

tiku:
    homework-url: http://tikuapp.ljtest.hqjy.com/page/assess.html
    parse-url: http://tikuappprep.ljtest.hqjy.com/page/assess_report.html

mq:
    host: 10.0.98.46       #10.0.98.18
    port: 5672
    username: admin
    password: mon4498

#推送到蓝鲸生成订单队列
nc-sign-sync-common: nc.sign.sync.common