# EMBEDDED SERVER CONFIGURATION (ServerProperties)

server:
    port: 8084
    address: 0.0.0.0
    session-timeout: 30
    compression:
        enabled: true
    undertow:
        access-log-dir: /logs/access/
        access-log-enabled: false
        access-log-pattern: common
        buffer-size: 10240
        buffers-per-region:
        direct-buffers: true
        io-threads: 2
        worker-threads: 100
logging:
    path: /logs
    file: /logs/ssocenter.log
    level:
       com:
           elise:
               singlesignoncenter:
                   controller: INFO
                   config: INFO

spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://10.0.98.5:3306/hq_school?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        password: root
        username: root
        driver-class-name: com.mysql.jdbc.Driver
        minimum-idle: 5
        maximum-pool-size: 20
        idle-timeout: 600000
        connection-timeout: 30000
        max-lifetime: 1800000
    redis:
        enabled: true
        # 指定连接工厂使用的Database index，默认为: 0
        database: 4
        # 指定Redis server host，默认为: localhost
        host: 10.0.98.9
        # 指定redis服务端端口，默认: 6379
        port: 6384
        # 指定Redis server的密码
        # password:
        use-pool: true
        pool:
            # 指定连接池最大的活跃连接数，-1表示无限，默认为8
            max-active: 8
            # 指定当连接池耗尽时，新获取连接需要等待的最大时间，以毫秒单位，-1表示无限等待
            max-wait: 5000
            # 指定连接池最大的空闲连接数，-1表示无限，默认为8
            min-idle: 8
        # sentinel:
            # 指定redis server的名称
            # master:
            # 指定sentinel节点，逗号分隔，格式为host:port.
            # nodes:
        # 指定连接超时时间，毫秒单位，默认为0
        timeout: 10000

local-info:
    # Token超时以天为单位
    token-expired-time: 30
    # OTP部分超时以分钟为单位
    otp-sms-max-expire-time: 10
    # OTP时间间隔以秒为单位
    otp-sms-max-gap-time: 60
    # OTP最大次数
    opt-sms-max-count: 10
    # OTP短信下发开关
    otp-sms-switch: false
    # OTP万能口令
    otp-pass-key: 1111
    # Default Portrait
    default-avatar-url: http://zikao.hqjy.com/Avatar.png
    # 密码验证请求最大次数
    check-password-max-count: 5
    # 密码验证次数保存时间,单位分钟
    password-max-timeout: 30

uig:
    name-space: users
    offset: 10020000
    step: 10

swagger:
    enable: true
    title-name: SSO Center 接口文档
    base-package: com.elise.singlesignoncenter
    author: Glenn
    version: 1.0

# IP 白名单
ip-white-list:
    filter-switch: false
    list:
          - 8.8.8.8
          - 0.0.0.0
          - 127.0.0.1
          - 0:0:0:0:0:0:0:1
          - 177.77.83.149
 #消息系统的请求路径
domain:
    msg-host: http://172.16.3.1/service-msg-api