package com.school.accountant.dao;

import com.school.accountant.entity.NewsAdvert;
import com.school.accountant.entity.NewsAdvertExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface NewsAdvertMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_advert
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    int countByExample(NewsAdvertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_advert
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    int deleteByExample(NewsAdvertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_advert
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    int deleteByPrimaryKey(Integer advertid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_advert
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    int insert(NewsAdvert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_advert
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    int insertSelective(NewsAdvert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_advert
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    List<NewsAdvert> selectByExampleWithBLOBsWithRowbounds(NewsAdvertExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_advert
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    List<NewsAdvert> selectByExampleWithBLOBs(NewsAdvertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_advert
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    List<NewsAdvert> selectByExampleWithRowbounds(NewsAdvertExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_advert
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    List<NewsAdvert> selectByExample(NewsAdvertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_advert
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    NewsAdvert selectByPrimaryKey(Integer advertid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_advert
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    int updateByExampleSelective(@Param("record") NewsAdvert record, @Param("example") NewsAdvertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_advert
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") NewsAdvert record, @Param("example") NewsAdvertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_advert
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    int updateByExample(@Param("record") NewsAdvert record, @Param("example") NewsAdvertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_advert
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    int updateByPrimaryKeySelective(NewsAdvert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_advert
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(NewsAdvert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_advert
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    int updateByPrimaryKey(NewsAdvert record);
}