package com.school.accountant.vo;

import java.io.Serializable;
import java.util.Date;

import com.alibaba.fastjson.annotation.JSONField;

public class MallProductVo implements Serializable{
    
	private static final long serialVersionUID = 7557935100474294163L;

	public Integer Id;
	
    private Integer productid;
    
    /**
     * 关联实训
     */
    private Integer practiceid;
    
    private String productname;

    private Integer typeid;

    private String photo;

    private String summary;

    private Double score;

    private Integer content;

    private String similarProductsid;
    
    private String probationAccountId;

    private Integer validity;

    private String unit;

    private Double price;

    private Double originalPrice;

    private Double preferentialPrice;

    private Double experiencePrice;

    private Double discounts;

    private Double originalPoints;

    private Double points;

    private String tag;

    @JSONField (format="yyyy-MM-dd HH:mm:ss") 
    private Date upShelvesTime;

    @JSONField (format="yyyy-MM-dd HH:mm:ss") 
    private Date downShelvesTime;

    private Boolean isrecommend;

    private Boolean isnew;

    private Boolean ishot;

    private Boolean isshelves;

    private Boolean iscashback;

    private String seotitle;

    private String seodescription;

    private String seokeywords;

    @JSONField (format="yyyy-MM-dd HH:mm:ss") 
    private Date creationtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_product.dr
     *
     * @mbggenerated
     */
    private Integer dr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_product.ts
     *
     * @mbggenerated
     */
    @JSONField (format="yyyy-MM-dd HH:mm:ss") 
    private Date ts;
    
    private Integer creator;
    
    private String creatorname;
    
    private Integer modifier;
    
    private String modifiername;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product.productid
     *
     * @return the value of mall_product.productid
     *
     * @mbggenerated
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product.productid
     *
     * @param productid the value for mall_product.productid
     *
     * @mbggenerated
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    public Integer getPracticeid() {
		return practiceid;
	}

	public void setPracticeid(Integer practiceid) {
		this.practiceid = practiceid;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product.productname
     *
     * @return the value of mall_product.productname
     *
     * @mbggenerated
     */
    public String getProductname() {
        return productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product.productname
     *
     * @param productname the value for mall_product.productname
     *
     * @mbggenerated
     */
    public void setProductname(String productname) {
        this.productname = productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product.typeid
     *
     * @return the value of mall_product.typeid
     *
     * @mbggenerated
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product.typeid
     *
     * @param typeid the value for mall_product.typeid
     *
     * @mbggenerated
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product.photo
     *
     * @return the value of mall_product.photo
     *
     * @mbggenerated
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product.photo
     *
     * @param photo the value for mall_product.photo
     *
     * @mbggenerated
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product.summary
     *
     * @return the value of mall_product.summary
     *
     * @mbggenerated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product.summary
     *
     * @param summary the value for mall_product.summary
     *
     * @mbggenerated
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product.score
     *
     * @return the value of mall_product.score
     *
     * @mbggenerated
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product.score
     *
     * @param score the value for mall_product.score
     *
     * @mbggenerated
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product.content
     *
     * @return the value of mall_product.content
     *
     * @mbggenerated
     */
    public Integer getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product.content
     *
     * @param content the value for mall_product.content
     *
     * @mbggenerated
     */
    public void setContent(Integer content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product.similar_productsid
     *
     * @return the value of mall_product.similar_productsid
     *
     * @mbggenerated
     */
    public String getSimilarProductsid() {
        return similarProductsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product.similar_productsid
     *
     * @param similarProductsid the value for mall_product.similar_productsid
     *
     * @mbggenerated
     */
    public void setSimilarProductsid(String similarProductsid) {
        this.similarProductsid = similarProductsid == null ? null : similarProductsid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product.validity
     *
     * @return the value of mall_product.validity
     *
     * @mbggenerated
     */
    public Integer getValidity() {
        return validity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product.validity
     *
     * @param validity the value for mall_product.validity
     *
     * @mbggenerated
     */
    public void setValidity(Integer validity) {
        this.validity = validity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product.unit
     *
     * @return the value of mall_product.unit
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product.unit
     *
     * @param unit the value for mall_product.unit
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product.price
     *
     * @return the value of mall_product.price
     *
     * @mbggenerated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product.price
     *
     * @param price the value for mall_product.price
     *
     * @mbggenerated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product.original_price
     *
     * @return the value of mall_product.original_price
     *
     * @mbggenerated
     */
    public Double getOriginalPrice() {
        return originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product.original_price
     *
     * @param originalPrice the value for mall_product.original_price
     *
     * @mbggenerated
     */
    public void setOriginalPrice(Double originalPrice) {
        this.originalPrice = originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product.preferential_price
     *
     * @return the value of mall_product.preferential_price
     *
     * @mbggenerated
     */
    public Double getPreferentialPrice() {
        return preferentialPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product.preferential_price
     *
     * @param preferentialPrice the value for mall_product.preferential_price
     *
     * @mbggenerated
     */
    public void setPreferentialPrice(Double preferentialPrice) {
        this.preferentialPrice = preferentialPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product.experience_price
     *
     * @return the value of mall_product.experience_price
     *
     * @mbggenerated
     */
    public Double getExperiencePrice() {
        return experiencePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product.experience_price
     *
     * @param experiencePrice the value for mall_product.experience_price
     *
     * @mbggenerated
     */
    public void setExperiencePrice(Double experiencePrice) {
        this.experiencePrice = experiencePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product.discounts
     *
     * @return the value of mall_product.discounts
     *
     * @mbggenerated
     */
    public Double getDiscounts() {
        return discounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product.discounts
     *
     * @param discounts the value for mall_product.discounts
     *
     * @mbggenerated
     */
    public void setDiscounts(Double discounts) {
        this.discounts = discounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product.original_points
     *
     * @return the value of mall_product.original_points
     *
     * @mbggenerated
     */
    public Double getOriginalPoints() {
        return originalPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product.original_points
     *
     * @param originalPoints the value for mall_product.original_points
     *
     * @mbggenerated
     */
    public void setOriginalPoints(Double originalPoints) {
        this.originalPoints = originalPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product.points
     *
     * @return the value of mall_product.points
     *
     * @mbggenerated
     */
    public Double getPoints() {
        return points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product.points
     *
     * @param points the value for mall_product.points
     *
     * @mbggenerated
     */
    public void setPoints(Double points) {
        this.points = points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product.tag
     *
     * @return the value of mall_product.tag
     *
     * @mbggenerated
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product.tag
     *
     * @param tag the value for mall_product.tag
     *
     * @mbggenerated
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product.up_shelves_time
     *
     * @return the value of mall_product.up_shelves_time
     *
     * @mbggenerated
     */
    public Date getUpShelvesTime() {
        return upShelvesTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product.up_shelves_time
     *
     * @param upShelvesTime the value for mall_product.up_shelves_time
     *
     * @mbggenerated
     */
    public void setUpShelvesTime(Date upShelvesTime) {
        this.upShelvesTime = upShelvesTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product.down_shelves_time
     *
     * @return the value of mall_product.down_shelves_time
     *
     * @mbggenerated
     */
    public Date getDownShelvesTime() {
        return downShelvesTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product.down_shelves_time
     *
     * @param downShelvesTime the value for mall_product.down_shelves_time
     *
     * @mbggenerated
     */
    public void setDownShelvesTime(Date downShelvesTime) {
        this.downShelvesTime = downShelvesTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product.isrecommend
     *
     * @return the value of mall_product.isrecommend
     *
     * @mbggenerated
     */
    public Boolean getIsrecommend() {
        return isrecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product.isrecommend
     *
     * @param isrecommend the value for mall_product.isrecommend
     *
     * @mbggenerated
     */
    public void setIsrecommend(Boolean isrecommend) {
        this.isrecommend = isrecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product.isnew
     *
     * @return the value of mall_product.isnew
     *
     * @mbggenerated
     */
    public Boolean getIsnew() {
        return isnew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product.isnew
     *
     * @param isnew the value for mall_product.isnew
     *
     * @mbggenerated
     */
    public void setIsnew(Boolean isnew) {
        this.isnew = isnew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product.ishot
     *
     * @return the value of mall_product.ishot
     *
     * @mbggenerated
     */
    public Boolean getIshot() {
        return ishot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product.ishot
     *
     * @param ishot the value for mall_product.ishot
     *
     * @mbggenerated
     */
    public void setIshot(Boolean ishot) {
        this.ishot = ishot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product.isshelves
     *
     * @return the value of mall_product.isshelves
     *
     * @mbggenerated
     */
    public Boolean getIsshelves() {
        return isshelves;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product.isshelves
     *
     * @param isshelves the value for mall_product.isshelves
     *
     * @mbggenerated
     */
    public void setIsshelves(Boolean isshelves) {
        this.isshelves = isshelves;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product.iscashback
     *
     * @return the value of mall_product.iscashback
     *
     * @mbggenerated
     */
    public Boolean getIscashback() {
        return iscashback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product.iscashback
     *
     * @param iscashback the value for mall_product.iscashback
     *
     * @mbggenerated
     */
    public void setIscashback(Boolean iscashback) {
        this.iscashback = iscashback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product.seotitle
     *
     * @return the value of mall_product.seotitle
     *
     * @mbggenerated
     */
    public String getSeotitle() {
        return seotitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product.seotitle
     *
     * @param seotitle the value for mall_product.seotitle
     *
     * @mbggenerated
     */
    public void setSeotitle(String seotitle) {
        this.seotitle = seotitle == null ? null : seotitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product.seodescription
     *
     * @return the value of mall_product.seodescription
     *
     * @mbggenerated
     */
    public String getSeodescription() {
        return seodescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product.seodescription
     *
     * @param seodescription the value for mall_product.seodescription
     *
     * @mbggenerated
     */
    public void setSeodescription(String seodescription) {
        this.seodescription = seodescription == null ? null : seodescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product.seokeywords
     *
     * @return the value of mall_product.seokeywords
     *
     * @mbggenerated
     */
    public String getSeokeywords() {
        return seokeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product.seokeywords
     *
     * @param seokeywords the value for mall_product.seokeywords
     *
     * @mbggenerated
     */
    public void setSeokeywords(String seokeywords) {
        this.seokeywords = seokeywords == null ? null : seokeywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product.creationtime
     *
     * @return the value of mall_product.creationtime
     *
     * @mbggenerated
     */
    public Date getCreationtime() {
        return creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product.creationtime
     *
     * @param creationtime the value for mall_product.creationtime
     *
     * @mbggenerated
     */
    public void setCreationtime(Date creationtime) {
        this.creationtime = creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product.dr
     *
     * @return the value of mall_product.dr
     *
     * @mbggenerated
     */
    public Integer getDr() {
        return dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product.dr
     *
     * @param dr the value for mall_product.dr
     *
     * @mbggenerated
     */
    public void setDr(Integer dr) {
        this.dr = dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product.ts
     *
     * @return the value of mall_product.ts
     *
     * @mbggenerated
     */
    public Date getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product.ts
     *
     * @param ts the value for mall_product.ts
     *
     * @mbggenerated
     */
    public void setTs(Date ts) {
        this.ts = ts;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_defitem.creator
     *
     * @return the value of sys_defitem.creator
     *
     * @mbggenerated
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_defitem.creator
     *
     * @param creator the value for sys_defitem.creator
     *
     * @mbggenerated
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_defitem.creatorname
     *
     * @return the value of sys_defitem.creatorname
     *
     * @mbggenerated
     */
	public String getCreatorname() {
		return creatorname;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_defitem.creatorname
     *
     * @param ts the value for sys_defitem.creatorname
     *
     * @mbggenerated
     */
	public void setCreatorname(String creatorname) {
		this.creatorname = creatorname;
	}
	
	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_defitem.modifier
     *
     * @return the value of sys_defitem.modifier
     *
     * @mbggenerated
     */
    public Integer getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_defitem.modifier
     *
     * @param modifier the value for sys_defitem.modifier
     *
     * @mbggenerated
     */
    public void setModifier(Integer modifier) {
        this.modifier = modifier;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_defitem.modifiername
     *
     * @return the value of sys_defitem.modifiername
     *
     * @mbggenerated
     */
	public String getModifiername() {
		return modifiername;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_defitem.modifiername
     *
     * @param ts the value for sys_defitem.modifiername
     *
     * @mbggenerated
     */
	public void setModifiername(String modifiername) {
		this.modifiername = modifiername;
	}

	public Integer getId() {
		return getProductid();
	}

	public void setId(Integer id) {
		setProductid(id);
	}

	public String getProbationAccountId() {
		return probationAccountId;
	}

	public void setProbationAccountId(String probationAccountId) {
		this.probationAccountId = probationAccountId;
	}
}