package com.school.accountant.vo;

import java.io.Serializable;
import java.util.Date;

import com.alibaba.fastjson.annotation.JSONField;

/**
 * 实训系统学员已开通的账套
 * @author Administrator
 *
 */
public class PracticeLearnVo implements Serializable {

	private static final long serialVersionUID = -7530197180372300803L;

	public Integer Id;
	
	//主键
	private Integer learnid;
	
	/**
     * 实训名
     */
    private String name;

    /**
     * 商品摘要
     */
    private String summary;

    /**
     * 实训图片
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practice_learn.memberid
     *
     * @mbggenerated
     */
    private Integer memberid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practice_learn.practiceid
     *
     * @mbggenerated
     */
    private Integer practiceid;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practice_learn.accountid
     *
     * @mbggenerated
     */
    private Integer accountid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practice_learn.initializetime
     *
     * @mbggenerated
     */
    @JSONField (format="yyyy-MM-dd HH:mm:ss") 
    private Date initializetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practice_learn.practicetime
     *
     * @mbggenerated
     */
    @JSONField (format="yyyy-MM-dd HH:mm:ss") 
    private Date practicetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practice_learn.scorehight
     *
     * @mbggenerated
     */
    private Double scorehight;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practice_learn.scorelow
     *
     * @mbggenerated
     */
    private Double scorelow;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practice_learn.scoreavg
     *
     * @mbggenerated
     */
    private Double scoreavg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practice_learn.status
     * 实训状态：1：有效2：失效
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practice_learn.creationtime
     *
     * @mbggenerated
     */
    @JSONField (format="yyyy-MM-dd HH:mm:ss")
    private Date creationtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practice_learn.dr
     *
     * @mbggenerated
     */
    private Integer dr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practice_learn.ts
     *
     * @mbggenerated
     */
    @JSONField (format="yyyy-MM-dd HH:mm:ss") 
    private Date ts;

    /**
     * 有效期
     */
    @JSONField (format="yyyy-MM-dd HH:mm:ss") 
    private Date expirydate;
    
    /**
     * 开通类型 1：订单 2:NC 3:老师开通 4：特殊情况 
     */
    private Integer type;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practice_learn.learnid
     *
     * @return the value of practice_learn.learnid
     *
     * @mbggenerated
     */
    public Integer getLearnid() {
        return learnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practice_learn.learnid
     *
     * @param businessid the value for practice_learn.learnid
     *
     * @mbggenerated
     */
    public void setLearnid(Integer learnid) {
        this.learnid = learnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practice_learn.practiceid
     *
     * @return the value of practice_learn.practiceid
     *
     * @mbggenerated
     */
    public Integer getPracticeid() {
        return practiceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practice_learn.practiceid
     *
     * @param practiceid the value for practice_learn.practiceid
     *
     * @mbggenerated
     */
    public void setPracticeid(Integer practiceid) {
        this.practiceid = practiceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practice_learn.memberid
     *
     * @return the value of practice_learn.memberid
     *
     * @mbggenerated
     */
    public Integer getMemberid() {
        return memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practice_learn.memberid
     *
     * @param business the value for practice_learn.memberid
     *
     * @mbggenerated
     */
    public void setMemberid(Integer memberid) {
        this.memberid = memberid;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practice_learn.accountid
     *
     * @return the value of practice_learn.accountid
     *
     * @mbggenerated
     */
    public Integer getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practice_learn.accountid
     *
     * @param practiceid the value for practice_learn.accountid
     *
     * @mbggenerated
     */
    public void setAccountid(Integer accountid) {
        this.accountid = accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practice_learn.initializetime
     *
     * @return the value of practice_learn.initializetime
     *
     * @mbggenerated
     */
    public Date getInitializetime() {
        return initializetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practice_learn.initializetime
     *
     * @param description the value for practice_learn.initializetime
     *
     * @mbggenerated
     */
    public void setInitializetime(Date initializetime) {
        this.initializetime = initializetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practice_learn.practicetime
     *
     * @return the value of practice_learn.practicetime
     *
     * @mbggenerated
     */
    public Date getPracticetime() {
        return practicetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practice_learn.practicetime
     *
     * @param analyzation the value for practice_learn.practicetime
     *
     * @mbggenerated
     */
    public void setPracticetime(Date practicetime) {
        this.practicetime = practicetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practice_learn.scorehight
     *
     * @return the value of practice_learn.scorehight
     *
     * @mbggenerated
     */
    public Double getScorehight() {
        return scorehight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practice_learn.scorehight
     *
     * @param voucherid the value for practice_learn.scorehight
     *
     * @mbggenerated
     */
    public void setScorehight(Double scorehight) {
        this.scorehight = scorehight;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practice_learn.scorelow
     *
     * @return the value of practice_learn.scorelow
     *
     * @mbggenerated
     */
    public Double getScorelow() {
        return scorelow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practice_learn.scorelow
     *
     * @param voucherid the value for practice_learn.scorelow
     *
     * @mbggenerated
     */
    public void setScorelow(Double scorelow) {
        this.scorelow = scorelow;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practice_learn.scoreavg
     *
     * @return the value of practice_learn.scoreavg
     *
     * @mbggenerated
     */
    public Double getScoreavg() {
        return scoreavg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practice_learn.scoreavg
     *
     * @param voucherid the value for practice_learn.scoreavg
     *
     * @mbggenerated
     */
    public void setScoreavg(Double scoreavg) {
        this.scoreavg = scoreavg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practice_learn.status
     *
     * @return the value of practice_learn.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practice_learn.status
     *
     * @param status the value for practice_learn.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practice_learn.creationtime
     *
     * @return the value of practice_learn.creationtime
     *
     * @mbggenerated
     */
    public Date getCreationtime() {
        return creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practice_learn.creationtime
     *
     * @param creationtime the value for practice_learn.creationtime
     *
     * @mbggenerated
     */
    public void setCreationtime(Date creationtime) {
        this.creationtime = creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practice_learn.dr
     *
     * @return the value of practice_learn.dr
     *
     * @mbggenerated
     */
    public Integer getDr() {
        return dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practice_learn.dr
     *
     * @param dr the value for practice_learn.dr
     *
     * @mbggenerated
     */
    public void setDr(Integer dr) {
        this.dr = dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practice_learn.ts
     *
     * @return the value of practice_learn.ts
     *
     * @mbggenerated
     */
    public Date getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practice_learn.ts
     *
     * @param ts the value for practice_learn.ts
     *
     * @mbggenerated
     */
    public void setTs(Date ts) {
        this.ts = ts;
    }
    
    public Date getExpirydate() {
		return expirydate;
	}

	public void setExpirydate(Date expirydate) {
		this.expirydate = expirydate;
	}

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Integer getId() {
		return getLearnid();
	}

	public void setId(Integer id) {
	 setLearnid(id);
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSummary() {
		return summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	public String getImgUrl() {
		return imgUrl;
	}

	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}
}
