From tomcat:9-jre8

RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone

VOLUME /tmp

VOLUME /logs

ADD ./server.xml  $CATALINA_HOME/conf/server.xml



EXPOSE 8080

ADD ./target/accountant /home/service/web/accountant


#WORKDIR $CATALINA_HOME
#ENTRYPOINT [$CATALINA_HOME/bin/startup.sh", "run" ]
CMD ["catalina.sh", "run"]