package com.kuaiji.dao;

import com.kuaiji.entity.AppProvince;
import com.kuaiji.entity.AppProvinceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AppProvinceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app_province
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    int countByExample(AppProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app_province
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    int deleteByExample(AppProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app_province
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app_province
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    int insert(AppProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app_province
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    int insertSelective(AppProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app_province
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    List<AppProvince> selectByExampleWithRowbounds(AppProvinceExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app_province
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    List<AppProvince> selectByExample(AppProvinceExample example);

    AppProvince selectByExampleFetchOne(AppProvinceExample example);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app_province
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    AppProvince selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app_province
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    int updateByExampleSelective(@Param("record") AppProvince record, @Param("example") AppProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app_province
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    int updateByExample(@Param("record") AppProvince record, @Param("example") AppProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app_province
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    int updateByPrimaryKeySelective(AppProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app_province
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    int updateByPrimaryKey(AppProvince record);
}