spring:
  datasource:
    url: jdbc:mysql://10.0.98.5:3306/hq_pay?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    #url: jdbc:mysql://localhost:3306/hq_pay?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    #username: root
    #password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
paycofig: 
  zhfReturnUrl: http://test.pay.hqjy.com/alipay/callback/return
  zhfNotifyUrl: http://test.pay.hqjy.com/alipay/callback/notify
  config: dev
  wxReturnUrl: http://test.pay.hqjy.com/wxpay/callback/notify
  url: http://10.0.85.134:8089
