package com.school.accountant.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class NewsAdvertExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table news_advert
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table news_advert
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table news_advert
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_advert
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public NewsAdvertExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_advert
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_advert
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_advert
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_advert
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_advert
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_advert
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_advert
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_advert
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_advert
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_advert
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table news_advert
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        public void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        public void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        public void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andAdvertidIsNull() {
            addCriterion("advertid is null");
            return (Criteria) this;
        }

        public Criteria andAdvertidIsNotNull() {
            addCriterion("advertid is not null");
            return (Criteria) this;
        }

        public Criteria andAdvertidEqualTo(Integer value) {
            addCriterion("advertid =", value, "advertid");
            return (Criteria) this;
        }

        public Criteria andAdvertidNotEqualTo(Integer value) {
            addCriterion("advertid <>", value, "advertid");
            return (Criteria) this;
        }

        public Criteria andAdvertidGreaterThan(Integer value) {
            addCriterion("advertid >", value, "advertid");
            return (Criteria) this;
        }

        public Criteria andAdvertidGreaterThanOrEqualTo(Integer value) {
            addCriterion("advertid >=", value, "advertid");
            return (Criteria) this;
        }

        public Criteria andAdvertidLessThan(Integer value) {
            addCriterion("advertid <", value, "advertid");
            return (Criteria) this;
        }

        public Criteria andAdvertidLessThanOrEqualTo(Integer value) {
            addCriterion("advertid <=", value, "advertid");
            return (Criteria) this;
        }

        public Criteria andAdvertidIn(List<Integer> values) {
            addCriterion("advertid in", values, "advertid");
            return (Criteria) this;
        }

        public Criteria andAdvertidNotIn(List<Integer> values) {
            addCriterion("advertid not in", values, "advertid");
            return (Criteria) this;
        }

        public Criteria andAdvertidBetween(Integer value1, Integer value2) {
            addCriterion("advertid between", value1, value2, "advertid");
            return (Criteria) this;
        }

        public Criteria andAdvertidNotBetween(Integer value1, Integer value2) {
            addCriterion("advertid not between", value1, value2, "advertid");
            return (Criteria) this;
        }

        public Criteria andChannelidIsNull() {
            addCriterion("channelid is null");
            return (Criteria) this;
        }

        public Criteria andChannelidIsNotNull() {
            addCriterion("channelid is not null");
            return (Criteria) this;
        }

        public Criteria andChannelidEqualTo(Integer value) {
            addCriterion("channelid =", value, "channelid");
            return (Criteria) this;
        }

        public Criteria andChannelidNotEqualTo(Integer value) {
            addCriterion("channelid <>", value, "channelid");
            return (Criteria) this;
        }

        public Criteria andChannelidGreaterThan(Integer value) {
            addCriterion("channelid >", value, "channelid");
            return (Criteria) this;
        }

        public Criteria andChannelidGreaterThanOrEqualTo(Integer value) {
            addCriterion("channelid >=", value, "channelid");
            return (Criteria) this;
        }

        public Criteria andChannelidLessThan(Integer value) {
            addCriterion("channelid <", value, "channelid");
            return (Criteria) this;
        }

        public Criteria andChannelidLessThanOrEqualTo(Integer value) {
            addCriterion("channelid <=", value, "channelid");
            return (Criteria) this;
        }

        public Criteria andChannelidIn(List<Integer> values) {
            addCriterion("channelid in", values, "channelid");
            return (Criteria) this;
        }

        public Criteria andChannelidNotIn(List<Integer> values) {
            addCriterion("channelid not in", values, "channelid");
            return (Criteria) this;
        }

        public Criteria andChannelidBetween(Integer value1, Integer value2) {
            addCriterion("channelid between", value1, value2, "channelid");
            return (Criteria) this;
        }

        public Criteria andChannelidNotBetween(Integer value1, Integer value2) {
            addCriterion("channelid not between", value1, value2, "channelid");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("code like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("code not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andStartdateIsNull() {
            addCriterion("startdate is null");
            return (Criteria) this;
        }

        public Criteria andStartdateIsNotNull() {
            addCriterion("startdate is not null");
            return (Criteria) this;
        }

        public Criteria andStartdateEqualTo(Date value) {
            addCriterionForJDBCDate("startdate =", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("startdate <>", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateGreaterThan(Date value) {
            addCriterionForJDBCDate("startdate >", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("startdate >=", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateLessThan(Date value) {
            addCriterionForJDBCDate("startdate <", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("startdate <=", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateIn(List<Date> values) {
            addCriterionForJDBCDate("startdate in", values, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("startdate not in", values, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("startdate between", value1, value2, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("startdate not between", value1, value2, "startdate");
            return (Criteria) this;
        }

        public Criteria andEnddateIsNull() {
            addCriterion("enddate is null");
            return (Criteria) this;
        }

        public Criteria andEnddateIsNotNull() {
            addCriterion("enddate is not null");
            return (Criteria) this;
        }

        public Criteria andEnddateEqualTo(Date value) {
            addCriterionForJDBCDate("enddate =", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotEqualTo(Date value) {
            addCriterionForJDBCDate("enddate <>", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateGreaterThan(Date value) {
            addCriterionForJDBCDate("enddate >", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("enddate >=", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateLessThan(Date value) {
            addCriterionForJDBCDate("enddate <", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("enddate <=", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateIn(List<Date> values) {
            addCriterionForJDBCDate("enddate in", values, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotIn(List<Date> values) {
            addCriterionForJDBCDate("enddate not in", values, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("enddate between", value1, value2, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("enddate not between", value1, value2, "enddate");
            return (Criteria) this;
        }

        public Criteria andImgsrandomIsNull() {
            addCriterion("imgsrandom is null");
            return (Criteria) this;
        }

        public Criteria andImgsrandomIsNotNull() {
            addCriterion("imgsrandom is not null");
            return (Criteria) this;
        }

        public Criteria andImgsrandomEqualTo(String value) {
            addCriterion("imgsrandom =", value, "imgsrandom");
            return (Criteria) this;
        }

        public Criteria andImgsrandomNotEqualTo(String value) {
            addCriterion("imgsrandom <>", value, "imgsrandom");
            return (Criteria) this;
        }

        public Criteria andImgsrandomGreaterThan(String value) {
            addCriterion("imgsrandom >", value, "imgsrandom");
            return (Criteria) this;
        }

        public Criteria andImgsrandomGreaterThanOrEqualTo(String value) {
            addCriterion("imgsrandom >=", value, "imgsrandom");
            return (Criteria) this;
        }

        public Criteria andImgsrandomLessThan(String value) {
            addCriterion("imgsrandom <", value, "imgsrandom");
            return (Criteria) this;
        }

        public Criteria andImgsrandomLessThanOrEqualTo(String value) {
            addCriterion("imgsrandom <=", value, "imgsrandom");
            return (Criteria) this;
        }

        public Criteria andImgsrandomLike(String value) {
            addCriterion("imgsrandom like", value, "imgsrandom");
            return (Criteria) this;
        }

        public Criteria andImgsrandomNotLike(String value) {
            addCriterion("imgsrandom not like", value, "imgsrandom");
            return (Criteria) this;
        }

        public Criteria andImgsrandomIn(List<String> values) {
            addCriterion("imgsrandom in", values, "imgsrandom");
            return (Criteria) this;
        }

        public Criteria andImgsrandomNotIn(List<String> values) {
            addCriterion("imgsrandom not in", values, "imgsrandom");
            return (Criteria) this;
        }

        public Criteria andImgsrandomBetween(String value1, String value2) {
            addCriterion("imgsrandom between", value1, value2, "imgsrandom");
            return (Criteria) this;
        }

        public Criteria andImgsrandomNotBetween(String value1, String value2) {
            addCriterion("imgsrandom not between", value1, value2, "imgsrandom");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andSortorderIsNull() {
            addCriterion("sortorder is null");
            return (Criteria) this;
        }

        public Criteria andSortorderIsNotNull() {
            addCriterion("sortorder is not null");
            return (Criteria) this;
        }

        public Criteria andSortorderEqualTo(Integer value) {
            addCriterion("sortorder =", value, "sortorder");
            return (Criteria) this;
        }

        public Criteria andSortorderNotEqualTo(Integer value) {
            addCriterion("sortorder <>", value, "sortorder");
            return (Criteria) this;
        }

        public Criteria andSortorderGreaterThan(Integer value) {
            addCriterion("sortorder >", value, "sortorder");
            return (Criteria) this;
        }

        public Criteria andSortorderGreaterThanOrEqualTo(Integer value) {
            addCriterion("sortorder >=", value, "sortorder");
            return (Criteria) this;
        }

        public Criteria andSortorderLessThan(Integer value) {
            addCriterion("sortorder <", value, "sortorder");
            return (Criteria) this;
        }

        public Criteria andSortorderLessThanOrEqualTo(Integer value) {
            addCriterion("sortorder <=", value, "sortorder");
            return (Criteria) this;
        }

        public Criteria andSortorderIn(List<Integer> values) {
            addCriterion("sortorder in", values, "sortorder");
            return (Criteria) this;
        }

        public Criteria andSortorderNotIn(List<Integer> values) {
            addCriterion("sortorder not in", values, "sortorder");
            return (Criteria) this;
        }

        public Criteria andSortorderBetween(Integer value1, Integer value2) {
            addCriterion("sortorder between", value1, value2, "sortorder");
            return (Criteria) this;
        }

        public Criteria andSortorderNotBetween(Integer value1, Integer value2) {
            addCriterion("sortorder not between", value1, value2, "sortorder");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(Integer value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(Integer value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(Integer value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(Integer value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(Integer value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(Integer value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<Integer> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<Integer> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(Integer value1, Integer value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(Integer value1, Integer value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreationtimeIsNull() {
            addCriterion("creationtime is null");
            return (Criteria) this;
        }

        public Criteria andCreationtimeIsNotNull() {
            addCriterion("creationtime is not null");
            return (Criteria) this;
        }

        public Criteria andCreationtimeEqualTo(Date value) {
            addCriterion("creationtime =", value, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeNotEqualTo(Date value) {
            addCriterion("creationtime <>", value, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeGreaterThan(Date value) {
            addCriterion("creationtime >", value, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("creationtime >=", value, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeLessThan(Date value) {
            addCriterion("creationtime <", value, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeLessThanOrEqualTo(Date value) {
            addCriterion("creationtime <=", value, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeIn(List<Date> values) {
            addCriterion("creationtime in", values, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeNotIn(List<Date> values) {
            addCriterion("creationtime not in", values, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeBetween(Date value1, Date value2) {
            addCriterion("creationtime between", value1, value2, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeNotBetween(Date value1, Date value2) {
            addCriterion("creationtime not between", value1, value2, "creationtime");
            return (Criteria) this;
        }

        public Criteria andModifierIsNull() {
            addCriterion("modifier is null");
            return (Criteria) this;
        }

        public Criteria andModifierIsNotNull() {
            addCriterion("modifier is not null");
            return (Criteria) this;
        }

        public Criteria andModifierEqualTo(Integer value) {
            addCriterion("modifier =", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotEqualTo(Integer value) {
            addCriterion("modifier <>", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThan(Integer value) {
            addCriterion("modifier >", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThanOrEqualTo(Integer value) {
            addCriterion("modifier >=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThan(Integer value) {
            addCriterion("modifier <", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThanOrEqualTo(Integer value) {
            addCriterion("modifier <=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierIn(List<Integer> values) {
            addCriterion("modifier in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotIn(List<Integer> values) {
            addCriterion("modifier not in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierBetween(Integer value1, Integer value2) {
            addCriterion("modifier between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotBetween(Integer value1, Integer value2) {
            addCriterion("modifier not between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifiedtimeIsNull() {
            addCriterion("modifiedtime is null");
            return (Criteria) this;
        }

        public Criteria andModifiedtimeIsNotNull() {
            addCriterion("modifiedtime is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedtimeEqualTo(Date value) {
            addCriterion("modifiedtime =", value, "modifiedtime");
            return (Criteria) this;
        }

        public Criteria andModifiedtimeNotEqualTo(Date value) {
            addCriterion("modifiedtime <>", value, "modifiedtime");
            return (Criteria) this;
        }

        public Criteria andModifiedtimeGreaterThan(Date value) {
            addCriterion("modifiedtime >", value, "modifiedtime");
            return (Criteria) this;
        }

        public Criteria andModifiedtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modifiedtime >=", value, "modifiedtime");
            return (Criteria) this;
        }

        public Criteria andModifiedtimeLessThan(Date value) {
            addCriterion("modifiedtime <", value, "modifiedtime");
            return (Criteria) this;
        }

        public Criteria andModifiedtimeLessThanOrEqualTo(Date value) {
            addCriterion("modifiedtime <=", value, "modifiedtime");
            return (Criteria) this;
        }

        public Criteria andModifiedtimeIn(List<Date> values) {
            addCriterion("modifiedtime in", values, "modifiedtime");
            return (Criteria) this;
        }

        public Criteria andModifiedtimeNotIn(List<Date> values) {
            addCriterion("modifiedtime not in", values, "modifiedtime");
            return (Criteria) this;
        }

        public Criteria andModifiedtimeBetween(Date value1, Date value2) {
            addCriterion("modifiedtime between", value1, value2, "modifiedtime");
            return (Criteria) this;
        }

        public Criteria andModifiedtimeNotBetween(Date value1, Date value2) {
            addCriterion("modifiedtime not between", value1, value2, "modifiedtime");
            return (Criteria) this;
        }

        public Criteria andDrIsNull() {
            addCriterion("dr is null");
            return (Criteria) this;
        }

        public Criteria andDrIsNotNull() {
            addCriterion("dr is not null");
            return (Criteria) this;
        }

        public Criteria andDrEqualTo(Integer value) {
            addCriterion("dr =", value, "dr");
            return (Criteria) this;
        }

        public Criteria andDrNotEqualTo(Integer value) {
            addCriterion("dr <>", value, "dr");
            return (Criteria) this;
        }

        public Criteria andDrGreaterThan(Integer value) {
            addCriterion("dr >", value, "dr");
            return (Criteria) this;
        }

        public Criteria andDrGreaterThanOrEqualTo(Integer value) {
            addCriterion("dr >=", value, "dr");
            return (Criteria) this;
        }

        public Criteria andDrLessThan(Integer value) {
            addCriterion("dr <", value, "dr");
            return (Criteria) this;
        }

        public Criteria andDrLessThanOrEqualTo(Integer value) {
            addCriterion("dr <=", value, "dr");
            return (Criteria) this;
        }

        public Criteria andDrIn(List<Integer> values) {
            addCriterion("dr in", values, "dr");
            return (Criteria) this;
        }

        public Criteria andDrNotIn(List<Integer> values) {
            addCriterion("dr not in", values, "dr");
            return (Criteria) this;
        }

        public Criteria andDrBetween(Integer value1, Integer value2) {
            addCriterion("dr between", value1, value2, "dr");
            return (Criteria) this;
        }

        public Criteria andDrNotBetween(Integer value1, Integer value2) {
            addCriterion("dr not between", value1, value2, "dr");
            return (Criteria) this;
        }

        public Criteria andTsIsNull() {
            addCriterion("ts is null");
            return (Criteria) this;
        }

        public Criteria andTsIsNotNull() {
            addCriterion("ts is not null");
            return (Criteria) this;
        }

        public Criteria andTsEqualTo(Date value) {
            addCriterion("ts =", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsNotEqualTo(Date value) {
            addCriterion("ts <>", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsGreaterThan(Date value) {
            addCriterion("ts >", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsGreaterThanOrEqualTo(Date value) {
            addCriterion("ts >=", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsLessThan(Date value) {
            addCriterion("ts <", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsLessThanOrEqualTo(Date value) {
            addCriterion("ts <=", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsIn(List<Date> values) {
            addCriterion("ts in", values, "ts");
            return (Criteria) this;
        }

        public Criteria andTsNotIn(List<Date> values) {
            addCriterion("ts not in", values, "ts");
            return (Criteria) this;
        }

        public Criteria andTsBetween(Date value1, Date value2) {
            addCriterion("ts between", value1, value2, "ts");
            return (Criteria) this;
        }

        public Criteria andTsNotBetween(Date value1, Date value2) {
            addCriterion("ts not between", value1, value2, "ts");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContenturlIsNull() {
            addCriterion("contenturl is null");
            return (Criteria) this;
        }

        public Criteria andContenturlIsNotNull() {
            addCriterion("contenturl is not null");
            return (Criteria) this;
        }

        public Criteria andContenturlEqualTo(String value) {
            addCriterion("contenturl =", value, "contenturl");
            return (Criteria) this;
        }

        public Criteria andContenturlNotEqualTo(String value) {
            addCriterion("contenturl <>", value, "contenturl");
            return (Criteria) this;
        }

        public Criteria andContenturlGreaterThan(String value) {
            addCriterion("contenturl >", value, "contenturl");
            return (Criteria) this;
        }

        public Criteria andContenturlGreaterThanOrEqualTo(String value) {
            addCriterion("contenturl >=", value, "contenturl");
            return (Criteria) this;
        }

        public Criteria andContenturlLessThan(String value) {
            addCriterion("contenturl <", value, "contenturl");
            return (Criteria) this;
        }

        public Criteria andContenturlLessThanOrEqualTo(String value) {
            addCriterion("contenturl <=", value, "contenturl");
            return (Criteria) this;
        }

        public Criteria andContenturlLike(String value) {
            addCriterion("contenturl like", value, "contenturl");
            return (Criteria) this;
        }

        public Criteria andContenturlNotLike(String value) {
            addCriterion("contenturl not like", value, "contenturl");
            return (Criteria) this;
        }

        public Criteria andContenturlIn(List<String> values) {
            addCriterion("contenturl in", values, "contenturl");
            return (Criteria) this;
        }

        public Criteria andContenturlNotIn(List<String> values) {
            addCriterion("contenturl not in", values, "contenturl");
            return (Criteria) this;
        }

        public Criteria andContenturlBetween(String value1, String value2) {
            addCriterion("contenturl between", value1, value2, "contenturl");
            return (Criteria) this;
        }

        public Criteria andContenturlNotBetween(String value1, String value2) {
            addCriterion("contenturl not between", value1, value2, "contenturl");
            return (Criteria) this;
        }

        public Criteria andContentsizeIsNull() {
            addCriterion("contentsize is null");
            return (Criteria) this;
        }

        public Criteria andContentsizeIsNotNull() {
            addCriterion("contentsize is not null");
            return (Criteria) this;
        }

        public Criteria andContentsizeEqualTo(Integer value) {
            addCriterion("contentsize =", value, "contentsize");
            return (Criteria) this;
        }

        public Criteria andContentsizeNotEqualTo(Integer value) {
            addCriterion("contentsize <>", value, "contentsize");
            return (Criteria) this;
        }

        public Criteria andContentsizeGreaterThan(Integer value) {
            addCriterion("contentsize >", value, "contentsize");
            return (Criteria) this;
        }

        public Criteria andContentsizeGreaterThanOrEqualTo(Integer value) {
            addCriterion("contentsize >=", value, "contentsize");
            return (Criteria) this;
        }

        public Criteria andContentsizeLessThan(Integer value) {
            addCriterion("contentsize <", value, "contentsize");
            return (Criteria) this;
        }

        public Criteria andContentsizeLessThanOrEqualTo(Integer value) {
            addCriterion("contentsize <=", value, "contentsize");
            return (Criteria) this;
        }

        public Criteria andContentsizeIn(List<Integer> values) {
            addCriterion("contentsize in", values, "contentsize");
            return (Criteria) this;
        }

        public Criteria andContentsizeNotIn(List<Integer> values) {
            addCriterion("contentsize not in", values, "contentsize");
            return (Criteria) this;
        }

        public Criteria andContentsizeBetween(Integer value1, Integer value2) {
            addCriterion("contentsize between", value1, value2, "contentsize");
            return (Criteria) this;
        }

        public Criteria andContentsizeNotBetween(Integer value1, Integer value2) {
            addCriterion("contentsize not between", value1, value2, "contentsize");
            return (Criteria) this;
        }

        public Criteria andImgaddressIsNull() {
            addCriterion("imgaddress is null");
            return (Criteria) this;
        }

        public Criteria andImgaddressIsNotNull() {
            addCriterion("imgaddress is not null");
            return (Criteria) this;
        }

        public Criteria andImgaddressEqualTo(String value) {
            addCriterion("imgaddress =", value, "imgaddress");
            return (Criteria) this;
        }

        public Criteria andImgaddressNotEqualTo(String value) {
            addCriterion("imgaddress <>", value, "imgaddress");
            return (Criteria) this;
        }

        public Criteria andImgaddressGreaterThan(String value) {
            addCriterion("imgaddress >", value, "imgaddress");
            return (Criteria) this;
        }

        public Criteria andImgaddressGreaterThanOrEqualTo(String value) {
            addCriterion("imgaddress >=", value, "imgaddress");
            return (Criteria) this;
        }

        public Criteria andImgaddressLessThan(String value) {
            addCriterion("imgaddress <", value, "imgaddress");
            return (Criteria) this;
        }

        public Criteria andImgaddressLessThanOrEqualTo(String value) {
            addCriterion("imgaddress <=", value, "imgaddress");
            return (Criteria) this;
        }

        public Criteria andImgaddressLike(String value) {
            addCriterion("imgaddress like", value, "imgaddress");
            return (Criteria) this;
        }

        public Criteria andImgaddressNotLike(String value) {
            addCriterion("imgaddress not like", value, "imgaddress");
            return (Criteria) this;
        }

        public Criteria andImgaddressIn(List<String> values) {
            addCriterion("imgaddress in", values, "imgaddress");
            return (Criteria) this;
        }

        public Criteria andImgaddressNotIn(List<String> values) {
            addCriterion("imgaddress not in", values, "imgaddress");
            return (Criteria) this;
        }

        public Criteria andImgaddressBetween(String value1, String value2) {
            addCriterion("imgaddress between", value1, value2, "imgaddress");
            return (Criteria) this;
        }

        public Criteria andImgaddressNotBetween(String value1, String value2) {
            addCriterion("imgaddress not between", value1, value2, "imgaddress");
            return (Criteria) this;
        }

        public Criteria andImgurlIsNull() {
            addCriterion("imgurl is null");
            return (Criteria) this;
        }

        public Criteria andImgurlIsNotNull() {
            addCriterion("imgurl is not null");
            return (Criteria) this;
        }

        public Criteria andImgurlEqualTo(String value) {
            addCriterion("imgurl =", value, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlNotEqualTo(String value) {
            addCriterion("imgurl <>", value, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlGreaterThan(String value) {
            addCriterion("imgurl >", value, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlGreaterThanOrEqualTo(String value) {
            addCriterion("imgurl >=", value, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlLessThan(String value) {
            addCriterion("imgurl <", value, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlLessThanOrEqualTo(String value) {
            addCriterion("imgurl <=", value, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlLike(String value) {
            addCriterion("imgurl like", value, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlNotLike(String value) {
            addCriterion("imgurl not like", value, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlIn(List<String> values) {
            addCriterion("imgurl in", values, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlNotIn(List<String> values) {
            addCriterion("imgurl not in", values, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlBetween(String value1, String value2) {
            addCriterion("imgurl between", value1, value2, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlNotBetween(String value1, String value2) {
            addCriterion("imgurl not between", value1, value2, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgcontentIsNull() {
            addCriterion("imgcontent is null");
            return (Criteria) this;
        }

        public Criteria andImgcontentIsNotNull() {
            addCriterion("imgcontent is not null");
            return (Criteria) this;
        }

        public Criteria andImgcontentEqualTo(String value) {
            addCriterion("imgcontent =", value, "imgcontent");
            return (Criteria) this;
        }

        public Criteria andImgcontentNotEqualTo(String value) {
            addCriterion("imgcontent <>", value, "imgcontent");
            return (Criteria) this;
        }

        public Criteria andImgcontentGreaterThan(String value) {
            addCriterion("imgcontent >", value, "imgcontent");
            return (Criteria) this;
        }

        public Criteria andImgcontentGreaterThanOrEqualTo(String value) {
            addCriterion("imgcontent >=", value, "imgcontent");
            return (Criteria) this;
        }

        public Criteria andImgcontentLessThan(String value) {
            addCriterion("imgcontent <", value, "imgcontent");
            return (Criteria) this;
        }

        public Criteria andImgcontentLessThanOrEqualTo(String value) {
            addCriterion("imgcontent <=", value, "imgcontent");
            return (Criteria) this;
        }

        public Criteria andImgcontentLike(String value) {
            addCriterion("imgcontent like", value, "imgcontent");
            return (Criteria) this;
        }

        public Criteria andImgcontentNotLike(String value) {
            addCriterion("imgcontent not like", value, "imgcontent");
            return (Criteria) this;
        }

        public Criteria andImgcontentIn(List<String> values) {
            addCriterion("imgcontent in", values, "imgcontent");
            return (Criteria) this;
        }

        public Criteria andImgcontentNotIn(List<String> values) {
            addCriterion("imgcontent not in", values, "imgcontent");
            return (Criteria) this;
        }

        public Criteria andImgcontentBetween(String value1, String value2) {
            addCriterion("imgcontent between", value1, value2, "imgcontent");
            return (Criteria) this;
        }

        public Criteria andImgcontentNotBetween(String value1, String value2) {
            addCriterion("imgcontent not between", value1, value2, "imgcontent");
            return (Criteria) this;
        }

        public Criteria andImgheightIsNull() {
            addCriterion("imgheight is null");
            return (Criteria) this;
        }

        public Criteria andImgheightIsNotNull() {
            addCriterion("imgheight is not null");
            return (Criteria) this;
        }

        public Criteria andImgheightEqualTo(Integer value) {
            addCriterion("imgheight =", value, "imgheight");
            return (Criteria) this;
        }

        public Criteria andImgheightNotEqualTo(Integer value) {
            addCriterion("imgheight <>", value, "imgheight");
            return (Criteria) this;
        }

        public Criteria andImgheightGreaterThan(Integer value) {
            addCriterion("imgheight >", value, "imgheight");
            return (Criteria) this;
        }

        public Criteria andImgheightGreaterThanOrEqualTo(Integer value) {
            addCriterion("imgheight >=", value, "imgheight");
            return (Criteria) this;
        }

        public Criteria andImgheightLessThan(Integer value) {
            addCriterion("imgheight <", value, "imgheight");
            return (Criteria) this;
        }

        public Criteria andImgheightLessThanOrEqualTo(Integer value) {
            addCriterion("imgheight <=", value, "imgheight");
            return (Criteria) this;
        }

        public Criteria andImgheightIn(List<Integer> values) {
            addCriterion("imgheight in", values, "imgheight");
            return (Criteria) this;
        }

        public Criteria andImgheightNotIn(List<Integer> values) {
            addCriterion("imgheight not in", values, "imgheight");
            return (Criteria) this;
        }

        public Criteria andImgheightBetween(Integer value1, Integer value2) {
            addCriterion("imgheight between", value1, value2, "imgheight");
            return (Criteria) this;
        }

        public Criteria andImgheightNotBetween(Integer value1, Integer value2) {
            addCriterion("imgheight not between", value1, value2, "imgheight");
            return (Criteria) this;
        }

        public Criteria andImgwidthIsNull() {
            addCriterion("imgwidth is null");
            return (Criteria) this;
        }

        public Criteria andImgwidthIsNotNull() {
            addCriterion("imgwidth is not null");
            return (Criteria) this;
        }

        public Criteria andImgwidthEqualTo(Integer value) {
            addCriterion("imgwidth =", value, "imgwidth");
            return (Criteria) this;
        }

        public Criteria andImgwidthNotEqualTo(Integer value) {
            addCriterion("imgwidth <>", value, "imgwidth");
            return (Criteria) this;
        }

        public Criteria andImgwidthGreaterThan(Integer value) {
            addCriterion("imgwidth >", value, "imgwidth");
            return (Criteria) this;
        }

        public Criteria andImgwidthGreaterThanOrEqualTo(Integer value) {
            addCriterion("imgwidth >=", value, "imgwidth");
            return (Criteria) this;
        }

        public Criteria andImgwidthLessThan(Integer value) {
            addCriterion("imgwidth <", value, "imgwidth");
            return (Criteria) this;
        }

        public Criteria andImgwidthLessThanOrEqualTo(Integer value) {
            addCriterion("imgwidth <=", value, "imgwidth");
            return (Criteria) this;
        }

        public Criteria andImgwidthIn(List<Integer> values) {
            addCriterion("imgwidth in", values, "imgwidth");
            return (Criteria) this;
        }

        public Criteria andImgwidthNotIn(List<Integer> values) {
            addCriterion("imgwidth not in", values, "imgwidth");
            return (Criteria) this;
        }

        public Criteria andImgwidthBetween(Integer value1, Integer value2) {
            addCriterion("imgwidth between", value1, value2, "imgwidth");
            return (Criteria) this;
        }

        public Criteria andImgwidthNotBetween(Integer value1, Integer value2) {
            addCriterion("imgwidth not between", value1, value2, "imgwidth");
            return (Criteria) this;
        }

        public Criteria andFlashaddressIsNull() {
            addCriterion("flashaddress is null");
            return (Criteria) this;
        }

        public Criteria andFlashaddressIsNotNull() {
            addCriterion("flashaddress is not null");
            return (Criteria) this;
        }

        public Criteria andFlashaddressEqualTo(String value) {
            addCriterion("flashaddress =", value, "flashaddress");
            return (Criteria) this;
        }

        public Criteria andFlashaddressNotEqualTo(String value) {
            addCriterion("flashaddress <>", value, "flashaddress");
            return (Criteria) this;
        }

        public Criteria andFlashaddressGreaterThan(String value) {
            addCriterion("flashaddress >", value, "flashaddress");
            return (Criteria) this;
        }

        public Criteria andFlashaddressGreaterThanOrEqualTo(String value) {
            addCriterion("flashaddress >=", value, "flashaddress");
            return (Criteria) this;
        }

        public Criteria andFlashaddressLessThan(String value) {
            addCriterion("flashaddress <", value, "flashaddress");
            return (Criteria) this;
        }

        public Criteria andFlashaddressLessThanOrEqualTo(String value) {
            addCriterion("flashaddress <=", value, "flashaddress");
            return (Criteria) this;
        }

        public Criteria andFlashaddressLike(String value) {
            addCriterion("flashaddress like", value, "flashaddress");
            return (Criteria) this;
        }

        public Criteria andFlashaddressNotLike(String value) {
            addCriterion("flashaddress not like", value, "flashaddress");
            return (Criteria) this;
        }

        public Criteria andFlashaddressIn(List<String> values) {
            addCriterion("flashaddress in", values, "flashaddress");
            return (Criteria) this;
        }

        public Criteria andFlashaddressNotIn(List<String> values) {
            addCriterion("flashaddress not in", values, "flashaddress");
            return (Criteria) this;
        }

        public Criteria andFlashaddressBetween(String value1, String value2) {
            addCriterion("flashaddress between", value1, value2, "flashaddress");
            return (Criteria) this;
        }

        public Criteria andFlashaddressNotBetween(String value1, String value2) {
            addCriterion("flashaddress not between", value1, value2, "flashaddress");
            return (Criteria) this;
        }

        public Criteria andFlashheightIsNull() {
            addCriterion("flashheight is null");
            return (Criteria) this;
        }

        public Criteria andFlashheightIsNotNull() {
            addCriterion("flashheight is not null");
            return (Criteria) this;
        }

        public Criteria andFlashheightEqualTo(Integer value) {
            addCriterion("flashheight =", value, "flashheight");
            return (Criteria) this;
        }

        public Criteria andFlashheightNotEqualTo(Integer value) {
            addCriterion("flashheight <>", value, "flashheight");
            return (Criteria) this;
        }

        public Criteria andFlashheightGreaterThan(Integer value) {
            addCriterion("flashheight >", value, "flashheight");
            return (Criteria) this;
        }

        public Criteria andFlashheightGreaterThanOrEqualTo(Integer value) {
            addCriterion("flashheight >=", value, "flashheight");
            return (Criteria) this;
        }

        public Criteria andFlashheightLessThan(Integer value) {
            addCriterion("flashheight <", value, "flashheight");
            return (Criteria) this;
        }

        public Criteria andFlashheightLessThanOrEqualTo(Integer value) {
            addCriterion("flashheight <=", value, "flashheight");
            return (Criteria) this;
        }

        public Criteria andFlashheightIn(List<Integer> values) {
            addCriterion("flashheight in", values, "flashheight");
            return (Criteria) this;
        }

        public Criteria andFlashheightNotIn(List<Integer> values) {
            addCriterion("flashheight not in", values, "flashheight");
            return (Criteria) this;
        }

        public Criteria andFlashheightBetween(Integer value1, Integer value2) {
            addCriterion("flashheight between", value1, value2, "flashheight");
            return (Criteria) this;
        }

        public Criteria andFlashheightNotBetween(Integer value1, Integer value2) {
            addCriterion("flashheight not between", value1, value2, "flashheight");
            return (Criteria) this;
        }

        public Criteria andFlashwidthIsNull() {
            addCriterion("flashwidth is null");
            return (Criteria) this;
        }

        public Criteria andFlashwidthIsNotNull() {
            addCriterion("flashwidth is not null");
            return (Criteria) this;
        }

        public Criteria andFlashwidthEqualTo(Integer value) {
            addCriterion("flashwidth =", value, "flashwidth");
            return (Criteria) this;
        }

        public Criteria andFlashwidthNotEqualTo(Integer value) {
            addCriterion("flashwidth <>", value, "flashwidth");
            return (Criteria) this;
        }

        public Criteria andFlashwidthGreaterThan(Integer value) {
            addCriterion("flashwidth >", value, "flashwidth");
            return (Criteria) this;
        }

        public Criteria andFlashwidthGreaterThanOrEqualTo(Integer value) {
            addCriterion("flashwidth >=", value, "flashwidth");
            return (Criteria) this;
        }

        public Criteria andFlashwidthLessThan(Integer value) {
            addCriterion("flashwidth <", value, "flashwidth");
            return (Criteria) this;
        }

        public Criteria andFlashwidthLessThanOrEqualTo(Integer value) {
            addCriterion("flashwidth <=", value, "flashwidth");
            return (Criteria) this;
        }

        public Criteria andFlashwidthIn(List<Integer> values) {
            addCriterion("flashwidth in", values, "flashwidth");
            return (Criteria) this;
        }

        public Criteria andFlashwidthNotIn(List<Integer> values) {
            addCriterion("flashwidth not in", values, "flashwidth");
            return (Criteria) this;
        }

        public Criteria andFlashwidthBetween(Integer value1, Integer value2) {
            addCriterion("flashwidth between", value1, value2, "flashwidth");
            return (Criteria) this;
        }

        public Criteria andFlashwidthNotBetween(Integer value1, Integer value2) {
            addCriterion("flashwidth not between", value1, value2, "flashwidth");
            return (Criteria) this;
        }

        public Criteria andAdvertpositionIsNull() {
            addCriterion("advertposition is null");
            return (Criteria) this;
        }

        public Criteria andAdvertpositionIsNotNull() {
            addCriterion("advertposition is not null");
            return (Criteria) this;
        }

        public Criteria andAdvertpositionEqualTo(Integer value) {
            addCriterion("advertposition =", value, "advertposition");
            return (Criteria) this;
        }

        public Criteria andAdvertpositionNotEqualTo(Integer value) {
            addCriterion("advertposition <>", value, "advertposition");
            return (Criteria) this;
        }

        public Criteria andAdvertpositionGreaterThan(Integer value) {
            addCriterion("advertposition >", value, "advertposition");
            return (Criteria) this;
        }

        public Criteria andAdvertpositionGreaterThanOrEqualTo(Integer value) {
            addCriterion("advertposition >=", value, "advertposition");
            return (Criteria) this;
        }

        public Criteria andAdvertpositionLessThan(Integer value) {
            addCriterion("advertposition <", value, "advertposition");
            return (Criteria) this;
        }

        public Criteria andAdvertpositionLessThanOrEqualTo(Integer value) {
            addCriterion("advertposition <=", value, "advertposition");
            return (Criteria) this;
        }

        public Criteria andAdvertpositionIn(List<Integer> values) {
            addCriterion("advertposition in", values, "advertposition");
            return (Criteria) this;
        }

        public Criteria andAdvertpositionNotIn(List<Integer> values) {
            addCriterion("advertposition not in", values, "advertposition");
            return (Criteria) this;
        }

        public Criteria andAdvertpositionBetween(Integer value1, Integer value2) {
            addCriterion("advertposition between", value1, value2, "advertposition");
            return (Criteria) this;
        }

        public Criteria andAdvertpositionNotBetween(Integer value1, Integer value2) {
            addCriterion("advertposition not between", value1, value2, "advertposition");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table news_advert
     *
     * @mbggenerated do_not_delete_during_merge Tue Aug 01 15:06:53 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table news_advert
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}