package com.school.accountant.entity;

import java.io.Serializable;
import java.util.Date;

public class NewsAdvert implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_advert.advertid
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private Integer advertid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_advert.channelid
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private Integer channelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_advert.title
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_advert.code
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_advert.remark
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_advert.startdate
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private Date startdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_advert.enddate
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private Date enddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_advert.imgsrandom
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private String imgsrandom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_advert.status
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_advert.sortorder
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private Integer sortorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_advert.creator
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_advert.creationtime
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private Date creationtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_advert.modifier
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private Integer modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_advert.modifiedtime
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private Date modifiedtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_advert.dr
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private Integer dr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_advert.ts
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private Date ts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_advert.content
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_advert.contenturl
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private String contenturl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_advert.contentsize
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private Integer contentsize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_advert.imgaddress
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private String imgaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_advert.imgurl
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private String imgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_advert.imgcontent
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private String imgcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_advert.imgheight
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private Integer imgheight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_advert.imgwidth
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private Integer imgwidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_advert.flashaddress
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private String flashaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_advert.flashheight
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private Integer flashheight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_advert.flashwidth
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private Integer flashwidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_advert.advertposition
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private Integer advertposition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_advert.html
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private String html;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table news_advert
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_advert.advertid
     *
     * @return the value of news_advert.advertid
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public Integer getAdvertid() {
        return advertid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_advert.advertid
     *
     * @param advertid the value for news_advert.advertid
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setAdvertid(Integer advertid) {
        this.advertid = advertid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_advert.channelid
     *
     * @return the value of news_advert.channelid
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public Integer getChannelid() {
        return channelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_advert.channelid
     *
     * @param channelid the value for news_advert.channelid
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setChannelid(Integer channelid) {
        this.channelid = channelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_advert.title
     *
     * @return the value of news_advert.title
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_advert.title
     *
     * @param title the value for news_advert.title
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_advert.code
     *
     * @return the value of news_advert.code
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_advert.code
     *
     * @param code the value for news_advert.code
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_advert.remark
     *
     * @return the value of news_advert.remark
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_advert.remark
     *
     * @param remark the value for news_advert.remark
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_advert.startdate
     *
     * @return the value of news_advert.startdate
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_advert.startdate
     *
     * @param startdate the value for news_advert.startdate
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_advert.enddate
     *
     * @return the value of news_advert.enddate
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public Date getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_advert.enddate
     *
     * @param enddate the value for news_advert.enddate
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_advert.imgsrandom
     *
     * @return the value of news_advert.imgsrandom
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public String getImgsrandom() {
        return imgsrandom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_advert.imgsrandom
     *
     * @param imgsrandom the value for news_advert.imgsrandom
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setImgsrandom(String imgsrandom) {
        this.imgsrandom = imgsrandom == null ? null : imgsrandom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_advert.status
     *
     * @return the value of news_advert.status
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_advert.status
     *
     * @param status the value for news_advert.status
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_advert.sortorder
     *
     * @return the value of news_advert.sortorder
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public Integer getSortorder() {
        return sortorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_advert.sortorder
     *
     * @param sortorder the value for news_advert.sortorder
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setSortorder(Integer sortorder) {
        this.sortorder = sortorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_advert.creator
     *
     * @return the value of news_advert.creator
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_advert.creator
     *
     * @param creator the value for news_advert.creator
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_advert.creationtime
     *
     * @return the value of news_advert.creationtime
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public Date getCreationtime() {
        return creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_advert.creationtime
     *
     * @param creationtime the value for news_advert.creationtime
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setCreationtime(Date creationtime) {
        this.creationtime = creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_advert.modifier
     *
     * @return the value of news_advert.modifier
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public Integer getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_advert.modifier
     *
     * @param modifier the value for news_advert.modifier
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setModifier(Integer modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_advert.modifiedtime
     *
     * @return the value of news_advert.modifiedtime
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public Date getModifiedtime() {
        return modifiedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_advert.modifiedtime
     *
     * @param modifiedtime the value for news_advert.modifiedtime
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setModifiedtime(Date modifiedtime) {
        this.modifiedtime = modifiedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_advert.dr
     *
     * @return the value of news_advert.dr
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public Integer getDr() {
        return dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_advert.dr
     *
     * @param dr the value for news_advert.dr
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setDr(Integer dr) {
        this.dr = dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_advert.ts
     *
     * @return the value of news_advert.ts
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public Date getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_advert.ts
     *
     * @param ts the value for news_advert.ts
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setTs(Date ts) {
        this.ts = ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_advert.content
     *
     * @return the value of news_advert.content
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_advert.content
     *
     * @param content the value for news_advert.content
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_advert.contenturl
     *
     * @return the value of news_advert.contenturl
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public String getContenturl() {
        return contenturl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_advert.contenturl
     *
     * @param contenturl the value for news_advert.contenturl
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setContenturl(String contenturl) {
        this.contenturl = contenturl == null ? null : contenturl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_advert.contentsize
     *
     * @return the value of news_advert.contentsize
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public Integer getContentsize() {
        return contentsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_advert.contentsize
     *
     * @param contentsize the value for news_advert.contentsize
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setContentsize(Integer contentsize) {
        this.contentsize = contentsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_advert.imgaddress
     *
     * @return the value of news_advert.imgaddress
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public String getImgaddress() {
        return imgaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_advert.imgaddress
     *
     * @param imgaddress the value for news_advert.imgaddress
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setImgaddress(String imgaddress) {
        this.imgaddress = imgaddress == null ? null : imgaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_advert.imgurl
     *
     * @return the value of news_advert.imgurl
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_advert.imgurl
     *
     * @param imgurl the value for news_advert.imgurl
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_advert.imgcontent
     *
     * @return the value of news_advert.imgcontent
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public String getImgcontent() {
        return imgcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_advert.imgcontent
     *
     * @param imgcontent the value for news_advert.imgcontent
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setImgcontent(String imgcontent) {
        this.imgcontent = imgcontent == null ? null : imgcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_advert.imgheight
     *
     * @return the value of news_advert.imgheight
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public Integer getImgheight() {
        return imgheight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_advert.imgheight
     *
     * @param imgheight the value for news_advert.imgheight
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setImgheight(Integer imgheight) {
        this.imgheight = imgheight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_advert.imgwidth
     *
     * @return the value of news_advert.imgwidth
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public Integer getImgwidth() {
        return imgwidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_advert.imgwidth
     *
     * @param imgwidth the value for news_advert.imgwidth
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setImgwidth(Integer imgwidth) {
        this.imgwidth = imgwidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_advert.flashaddress
     *
     * @return the value of news_advert.flashaddress
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public String getFlashaddress() {
        return flashaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_advert.flashaddress
     *
     * @param flashaddress the value for news_advert.flashaddress
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setFlashaddress(String flashaddress) {
        this.flashaddress = flashaddress == null ? null : flashaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_advert.flashheight
     *
     * @return the value of news_advert.flashheight
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public Integer getFlashheight() {
        return flashheight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_advert.flashheight
     *
     * @param flashheight the value for news_advert.flashheight
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setFlashheight(Integer flashheight) {
        this.flashheight = flashheight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_advert.flashwidth
     *
     * @return the value of news_advert.flashwidth
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public Integer getFlashwidth() {
        return flashwidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_advert.flashwidth
     *
     * @param flashwidth the value for news_advert.flashwidth
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setFlashwidth(Integer flashwidth) {
        this.flashwidth = flashwidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_advert.advertposition
     *
     * @return the value of news_advert.advertposition
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public Integer getAdvertposition() {
        return advertposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_advert.advertposition
     *
     * @param advertposition the value for news_advert.advertposition
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setAdvertposition(Integer advertposition) {
        this.advertposition = advertposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_advert.html
     *
     * @return the value of news_advert.html
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public String getHtml() {
        return html;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_advert.html
     *
     * @param html the value for news_advert.html
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setHtml(String html) {
        this.html = html == null ? null : html.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_advert
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", advertid=").append(advertid);
        sb.append(", channelid=").append(channelid);
        sb.append(", title=").append(title);
        sb.append(", code=").append(code);
        sb.append(", remark=").append(remark);
        sb.append(", startdate=").append(startdate);
        sb.append(", enddate=").append(enddate);
        sb.append(", imgsrandom=").append(imgsrandom);
        sb.append(", status=").append(status);
        sb.append(", sortorder=").append(sortorder);
        sb.append(", creator=").append(creator);
        sb.append(", creationtime=").append(creationtime);
        sb.append(", modifier=").append(modifier);
        sb.append(", modifiedtime=").append(modifiedtime);
        sb.append(", dr=").append(dr);
        sb.append(", ts=").append(ts);
        sb.append(", content=").append(content);
        sb.append(", contenturl=").append(contenturl);
        sb.append(", contentsize=").append(contentsize);
        sb.append(", imgaddress=").append(imgaddress);
        sb.append(", imgurl=").append(imgurl);
        sb.append(", imgcontent=").append(imgcontent);
        sb.append(", imgheight=").append(imgheight);
        sb.append(", imgwidth=").append(imgwidth);
        sb.append(", flashaddress=").append(flashaddress);
        sb.append(", flashheight=").append(flashheight);
        sb.append(", flashwidth=").append(flashwidth);
        sb.append(", advertposition=").append(advertposition);
        sb.append(", html=").append(html);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_advert
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        NewsAdvert other = (NewsAdvert) that;
        return (this.getAdvertid() == null ? other.getAdvertid() == null : this.getAdvertid().equals(other.getAdvertid()))
            && (this.getChannelid() == null ? other.getChannelid() == null : this.getChannelid().equals(other.getChannelid()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getStartdate() == null ? other.getStartdate() == null : this.getStartdate().equals(other.getStartdate()))
            && (this.getEnddate() == null ? other.getEnddate() == null : this.getEnddate().equals(other.getEnddate()))
            && (this.getImgsrandom() == null ? other.getImgsrandom() == null : this.getImgsrandom().equals(other.getImgsrandom()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getSortorder() == null ? other.getSortorder() == null : this.getSortorder().equals(other.getSortorder()))
            && (this.getCreator() == null ? other.getCreator() == null : this.getCreator().equals(other.getCreator()))
            && (this.getCreationtime() == null ? other.getCreationtime() == null : this.getCreationtime().equals(other.getCreationtime()))
            && (this.getModifier() == null ? other.getModifier() == null : this.getModifier().equals(other.getModifier()))
            && (this.getModifiedtime() == null ? other.getModifiedtime() == null : this.getModifiedtime().equals(other.getModifiedtime()))
            && (this.getDr() == null ? other.getDr() == null : this.getDr().equals(other.getDr()))
            && (this.getTs() == null ? other.getTs() == null : this.getTs().equals(other.getTs()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
            && (this.getContenturl() == null ? other.getContenturl() == null : this.getContenturl().equals(other.getContenturl()))
            && (this.getContentsize() == null ? other.getContentsize() == null : this.getContentsize().equals(other.getContentsize()))
            && (this.getImgaddress() == null ? other.getImgaddress() == null : this.getImgaddress().equals(other.getImgaddress()))
            && (this.getImgurl() == null ? other.getImgurl() == null : this.getImgurl().equals(other.getImgurl()))
            && (this.getImgcontent() == null ? other.getImgcontent() == null : this.getImgcontent().equals(other.getImgcontent()))
            && (this.getImgheight() == null ? other.getImgheight() == null : this.getImgheight().equals(other.getImgheight()))
            && (this.getImgwidth() == null ? other.getImgwidth() == null : this.getImgwidth().equals(other.getImgwidth()))
            && (this.getFlashaddress() == null ? other.getFlashaddress() == null : this.getFlashaddress().equals(other.getFlashaddress()))
            && (this.getFlashheight() == null ? other.getFlashheight() == null : this.getFlashheight().equals(other.getFlashheight()))
            && (this.getFlashwidth() == null ? other.getFlashwidth() == null : this.getFlashwidth().equals(other.getFlashwidth()))
            && (this.getAdvertposition() == null ? other.getAdvertposition() == null : this.getAdvertposition().equals(other.getAdvertposition()))
            && (this.getHtml() == null ? other.getHtml() == null : this.getHtml().equals(other.getHtml()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_advert
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAdvertid() == null) ? 0 : getAdvertid().hashCode());
        result = prime * result + ((getChannelid() == null) ? 0 : getChannelid().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getStartdate() == null) ? 0 : getStartdate().hashCode());
        result = prime * result + ((getEnddate() == null) ? 0 : getEnddate().hashCode());
        result = prime * result + ((getImgsrandom() == null) ? 0 : getImgsrandom().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getSortorder() == null) ? 0 : getSortorder().hashCode());
        result = prime * result + ((getCreator() == null) ? 0 : getCreator().hashCode());
        result = prime * result + ((getCreationtime() == null) ? 0 : getCreationtime().hashCode());
        result = prime * result + ((getModifier() == null) ? 0 : getModifier().hashCode());
        result = prime * result + ((getModifiedtime() == null) ? 0 : getModifiedtime().hashCode());
        result = prime * result + ((getDr() == null) ? 0 : getDr().hashCode());
        result = prime * result + ((getTs() == null) ? 0 : getTs().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getContenturl() == null) ? 0 : getContenturl().hashCode());
        result = prime * result + ((getContentsize() == null) ? 0 : getContentsize().hashCode());
        result = prime * result + ((getImgaddress() == null) ? 0 : getImgaddress().hashCode());
        result = prime * result + ((getImgurl() == null) ? 0 : getImgurl().hashCode());
        result = prime * result + ((getImgcontent() == null) ? 0 : getImgcontent().hashCode());
        result = prime * result + ((getImgheight() == null) ? 0 : getImgheight().hashCode());
        result = prime * result + ((getImgwidth() == null) ? 0 : getImgwidth().hashCode());
        result = prime * result + ((getFlashaddress() == null) ? 0 : getFlashaddress().hashCode());
        result = prime * result + ((getFlashheight() == null) ? 0 : getFlashheight().hashCode());
        result = prime * result + ((getFlashwidth() == null) ? 0 : getFlashwidth().hashCode());
        result = prime * result + ((getAdvertposition() == null) ? 0 : getAdvertposition().hashCode());
        result = prime * result + ((getHtml() == null) ? 0 : getHtml().hashCode());
        return result;
    }
}