package com.school.accountant.entity;

import java.io.Serializable;
import java.util.Date;

public class ProductType implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_product_type.typeid
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private Integer typeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_product_type.typename
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private String typename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_product_type.level
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_product_type.fatherid
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private Integer fatherid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_product_type.sortorder
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private Integer sortorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_product_type.isuse
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private Boolean isuse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_product_type.note
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_product_type.seoname
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private String seoname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_product_type.seo_title
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private String seoTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_product_type.seo_description
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private String seoDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_product_type.seo_keywords
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private String seoKeywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_product_type.creator
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_product_type.creationtime
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private Date creationtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_product_type.modifier
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private Integer modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_product_type.modifiedtime
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private Date modifiedtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_product_type.dr
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private Integer dr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_product_type.ts
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private Date ts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_product_type.qq
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_product_type.qqlink
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private String qqlink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_product_type.qqname
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private String qqname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_product_type.pic
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mall_product_type
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product_type.typeid
     *
     * @return the value of mall_product_type.typeid
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product_type.typeid
     *
     * @param typeid the value for mall_product_type.typeid
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product_type.typename
     *
     * @return the value of mall_product_type.typename
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public String getTypename() {
        return typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product_type.typename
     *
     * @param typename the value for mall_product_type.typename
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setTypename(String typename) {
        this.typename = typename == null ? null : typename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product_type.level
     *
     * @return the value of mall_product_type.level
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product_type.level
     *
     * @param level the value for mall_product_type.level
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product_type.fatherid
     *
     * @return the value of mall_product_type.fatherid
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public Integer getFatherid() {
        return fatherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product_type.fatherid
     *
     * @param fatherid the value for mall_product_type.fatherid
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setFatherid(Integer fatherid) {
        this.fatherid = fatherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product_type.sortorder
     *
     * @return the value of mall_product_type.sortorder
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public Integer getSortorder() {
        return sortorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product_type.sortorder
     *
     * @param sortorder the value for mall_product_type.sortorder
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setSortorder(Integer sortorder) {
        this.sortorder = sortorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product_type.isuse
     *
     * @return the value of mall_product_type.isuse
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public Boolean getIsuse() {
        return isuse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product_type.isuse
     *
     * @param isuse the value for mall_product_type.isuse
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setIsuse(Boolean isuse) {
        this.isuse = isuse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product_type.note
     *
     * @return the value of mall_product_type.note
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product_type.note
     *
     * @param note the value for mall_product_type.note
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product_type.seoname
     *
     * @return the value of mall_product_type.seoname
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public String getSeoname() {
        return seoname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product_type.seoname
     *
     * @param seoname the value for mall_product_type.seoname
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setSeoname(String seoname) {
        this.seoname = seoname == null ? null : seoname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product_type.seo_title
     *
     * @return the value of mall_product_type.seo_title
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public String getSeoTitle() {
        return seoTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product_type.seo_title
     *
     * @param seoTitle the value for mall_product_type.seo_title
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setSeoTitle(String seoTitle) {
        this.seoTitle = seoTitle == null ? null : seoTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product_type.seo_description
     *
     * @return the value of mall_product_type.seo_description
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public String getSeoDescription() {
        return seoDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product_type.seo_description
     *
     * @param seoDescription the value for mall_product_type.seo_description
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setSeoDescription(String seoDescription) {
        this.seoDescription = seoDescription == null ? null : seoDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product_type.seo_keywords
     *
     * @return the value of mall_product_type.seo_keywords
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public String getSeoKeywords() {
        return seoKeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product_type.seo_keywords
     *
     * @param seoKeywords the value for mall_product_type.seo_keywords
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setSeoKeywords(String seoKeywords) {
        this.seoKeywords = seoKeywords == null ? null : seoKeywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product_type.creator
     *
     * @return the value of mall_product_type.creator
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product_type.creator
     *
     * @param creator the value for mall_product_type.creator
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product_type.creationtime
     *
     * @return the value of mall_product_type.creationtime
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public Date getCreationtime() {
        return creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product_type.creationtime
     *
     * @param creationtime the value for mall_product_type.creationtime
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setCreationtime(Date creationtime) {
        this.creationtime = creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product_type.modifier
     *
     * @return the value of mall_product_type.modifier
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public Integer getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product_type.modifier
     *
     * @param modifier the value for mall_product_type.modifier
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setModifier(Integer modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product_type.modifiedtime
     *
     * @return the value of mall_product_type.modifiedtime
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public Date getModifiedtime() {
        return modifiedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product_type.modifiedtime
     *
     * @param modifiedtime the value for mall_product_type.modifiedtime
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setModifiedtime(Date modifiedtime) {
        this.modifiedtime = modifiedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product_type.dr
     *
     * @return the value of mall_product_type.dr
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public Integer getDr() {
        return dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product_type.dr
     *
     * @param dr the value for mall_product_type.dr
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setDr(Integer dr) {
        this.dr = dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product_type.ts
     *
     * @return the value of mall_product_type.ts
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public Date getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product_type.ts
     *
     * @param ts the value for mall_product_type.ts
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setTs(Date ts) {
        this.ts = ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product_type.qq
     *
     * @return the value of mall_product_type.qq
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product_type.qq
     *
     * @param qq the value for mall_product_type.qq
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product_type.qqlink
     *
     * @return the value of mall_product_type.qqlink
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public String getQqlink() {
        return qqlink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product_type.qqlink
     *
     * @param qqlink the value for mall_product_type.qqlink
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setQqlink(String qqlink) {
        this.qqlink = qqlink == null ? null : qqlink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product_type.qqname
     *
     * @return the value of mall_product_type.qqname
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public String getQqname() {
        return qqname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product_type.qqname
     *
     * @param qqname the value for mall_product_type.qqname
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setQqname(String qqname) {
        this.qqname = qqname == null ? null : qqname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product_type.pic
     *
     * @return the value of mall_product_type.pic
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product_type.pic
     *
     * @param pic the value for mall_product_type.pic
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_type
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", typeid=").append(typeid);
        sb.append(", typename=").append(typename);
        sb.append(", level=").append(level);
        sb.append(", fatherid=").append(fatherid);
        sb.append(", sortorder=").append(sortorder);
        sb.append(", isuse=").append(isuse);
        sb.append(", note=").append(note);
        sb.append(", seoname=").append(seoname);
        sb.append(", seoTitle=").append(seoTitle);
        sb.append(", seoDescription=").append(seoDescription);
        sb.append(", seoKeywords=").append(seoKeywords);
        sb.append(", creator=").append(creator);
        sb.append(", creationtime=").append(creationtime);
        sb.append(", modifier=").append(modifier);
        sb.append(", modifiedtime=").append(modifiedtime);
        sb.append(", dr=").append(dr);
        sb.append(", ts=").append(ts);
        sb.append(", qq=").append(qq);
        sb.append(", qqlink=").append(qqlink);
        sb.append(", qqname=").append(qqname);
        sb.append(", pic=").append(pic);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_type
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ProductType other = (ProductType) that;
        return (this.getTypeid() == null ? other.getTypeid() == null : this.getTypeid().equals(other.getTypeid()))
            && (this.getTypename() == null ? other.getTypename() == null : this.getTypename().equals(other.getTypename()))
            && (this.getLevel() == null ? other.getLevel() == null : this.getLevel().equals(other.getLevel()))
            && (this.getFatherid() == null ? other.getFatherid() == null : this.getFatherid().equals(other.getFatherid()))
            && (this.getSortorder() == null ? other.getSortorder() == null : this.getSortorder().equals(other.getSortorder()))
            && (this.getIsuse() == null ? other.getIsuse() == null : this.getIsuse().equals(other.getIsuse()))
            && (this.getNote() == null ? other.getNote() == null : this.getNote().equals(other.getNote()))
            && (this.getSeoname() == null ? other.getSeoname() == null : this.getSeoname().equals(other.getSeoname()))
            && (this.getSeoTitle() == null ? other.getSeoTitle() == null : this.getSeoTitle().equals(other.getSeoTitle()))
            && (this.getSeoDescription() == null ? other.getSeoDescription() == null : this.getSeoDescription().equals(other.getSeoDescription()))
            && (this.getSeoKeywords() == null ? other.getSeoKeywords() == null : this.getSeoKeywords().equals(other.getSeoKeywords()))
            && (this.getCreator() == null ? other.getCreator() == null : this.getCreator().equals(other.getCreator()))
            && (this.getCreationtime() == null ? other.getCreationtime() == null : this.getCreationtime().equals(other.getCreationtime()))
            && (this.getModifier() == null ? other.getModifier() == null : this.getModifier().equals(other.getModifier()))
            && (this.getModifiedtime() == null ? other.getModifiedtime() == null : this.getModifiedtime().equals(other.getModifiedtime()))
            && (this.getDr() == null ? other.getDr() == null : this.getDr().equals(other.getDr()))
            && (this.getTs() == null ? other.getTs() == null : this.getTs().equals(other.getTs()))
            && (this.getQq() == null ? other.getQq() == null : this.getQq().equals(other.getQq()))
            && (this.getQqlink() == null ? other.getQqlink() == null : this.getQqlink().equals(other.getQqlink()))
            && (this.getQqname() == null ? other.getQqname() == null : this.getQqname().equals(other.getQqname()))
            && (this.getPic() == null ? other.getPic() == null : this.getPic().equals(other.getPic()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_type
     *
     * @mbggenerated Tue Aug 01 15:06:53 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTypeid() == null) ? 0 : getTypeid().hashCode());
        result = prime * result + ((getTypename() == null) ? 0 : getTypename().hashCode());
        result = prime * result + ((getLevel() == null) ? 0 : getLevel().hashCode());
        result = prime * result + ((getFatherid() == null) ? 0 : getFatherid().hashCode());
        result = prime * result + ((getSortorder() == null) ? 0 : getSortorder().hashCode());
        result = prime * result + ((getIsuse() == null) ? 0 : getIsuse().hashCode());
        result = prime * result + ((getNote() == null) ? 0 : getNote().hashCode());
        result = prime * result + ((getSeoname() == null) ? 0 : getSeoname().hashCode());
        result = prime * result + ((getSeoTitle() == null) ? 0 : getSeoTitle().hashCode());
        result = prime * result + ((getSeoDescription() == null) ? 0 : getSeoDescription().hashCode());
        result = prime * result + ((getSeoKeywords() == null) ? 0 : getSeoKeywords().hashCode());
        result = prime * result + ((getCreator() == null) ? 0 : getCreator().hashCode());
        result = prime * result + ((getCreationtime() == null) ? 0 : getCreationtime().hashCode());
        result = prime * result + ((getModifier() == null) ? 0 : getModifier().hashCode());
        result = prime * result + ((getModifiedtime() == null) ? 0 : getModifiedtime().hashCode());
        result = prime * result + ((getDr() == null) ? 0 : getDr().hashCode());
        result = prime * result + ((getTs() == null) ? 0 : getTs().hashCode());
        result = prime * result + ((getQq() == null) ? 0 : getQq().hashCode());
        result = prime * result + ((getQqlink() == null) ? 0 : getQqlink().hashCode());
        result = prime * result + ((getQqname() == null) ? 0 : getQqname().hashCode());
        result = prime * result + ((getPic() == null) ? 0 : getPic().hashCode());
        return result;
    }
}