package com.hq.learningcenter.kuaiji.entity;

import java.io.Serializable;

public class AppProvince implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_app_province.id
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_app_province.nc_province_code
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    private String ncProvinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_app_province.kjl_province_code
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    private String kjlProvinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_app_province.province_name
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    private String provinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bd_app_province
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_app_province.id
     *
     * @return the value of bd_app_province.id
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_app_province.id
     *
     * @param id the value for bd_app_province.id
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_app_province.nc_province_code
     *
     * @return the value of bd_app_province.nc_province_code
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    public String getNcProvinceCode() {
        return ncProvinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_app_province.nc_province_code
     *
     * @param ncProvinceCode the value for bd_app_province.nc_province_code
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    public void setNcProvinceCode(String ncProvinceCode) {
        this.ncProvinceCode = ncProvinceCode == null ? null : ncProvinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_app_province.kjl_province_code
     *
     * @return the value of bd_app_province.kjl_province_code
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    public String getKjlProvinceCode() {
        return kjlProvinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_app_province.kjl_province_code
     *
     * @param kjlProvinceCode the value for bd_app_province.kjl_province_code
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    public void setKjlProvinceCode(String kjlProvinceCode) {
        this.kjlProvinceCode = kjlProvinceCode == null ? null : kjlProvinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_app_province.province_name
     *
     * @return the value of bd_app_province.province_name
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_app_province.province_name
     *
     * @param provinceName the value for bd_app_province.province_name
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app_province
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", ncProvinceCode=").append(ncProvinceCode);
        sb.append(", kjlProvinceCode=").append(kjlProvinceCode);
        sb.append(", provinceName=").append(provinceName);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app_province
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AppProvince other = (AppProvince) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getNcProvinceCode() == null ? other.getNcProvinceCode() == null : this.getNcProvinceCode().equals(other.getNcProvinceCode()))
            && (this.getKjlProvinceCode() == null ? other.getKjlProvinceCode() == null : this.getKjlProvinceCode().equals(other.getKjlProvinceCode()))
            && (this.getProvinceName() == null ? other.getProvinceName() == null : this.getProvinceName().equals(other.getProvinceName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app_province
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getNcProvinceCode() == null) ? 0 : getNcProvinceCode().hashCode());
        result = prime * result + ((getKjlProvinceCode() == null) ? 0 : getKjlProvinceCode().hashCode());
        result = prime * result + ((getProvinceName() == null) ? 0 : getProvinceName().hashCode());
        return result;
    }
}